/// All words are exactly 5 letters.
/// Crypto/trading terms are marked in comments.
class WordList {
  /// Answer words — these are the daily/random targets (crypto-focused).
  static const List<String> answerWords = [
    // Crypto & trading terms
    'token', 'yield', 'block', 'chain', 'miner', 'stake', 'vault', 'smart',
    'nonce', 'peers', 'nodes', 'pools', 'trade', 'whale', 'alpha', 'delta',
    'chart', 'rally', 'bears', 'bulls', 'short', 'longs', 'entry', 'exits',
    'limit', 'trail', 'order', 'funds', 'asset', 'bonds', 'forex', 'hedge',
    'index', 'price', 'quote', 'ratio', 'risks', 'sigma', 'theta', 'trend',
    'value', 'worth', 'xrays', 'yield', 'zksnk', 'batch', 'burns', 'coins',
    'debit', 'ether', 'forks', 'gains', 'halve', 'icate', 'jacks', 'kline',
    'layer', 'macro', 'nfted', 'offramp', 'proof', 'quant', 'relay', 'seeds',
    'tally', 'units', 'vests', 'wallt', 'xrplt', 'zcash',
    // Clean 5-letter crypto terms
    'defi', 'dapp', 'swap', 'pool', 'loan', 'burn', 'mint', 'lock',
    'seed', 'hash', 'fork', 'node', 'peer', 'vote', 'bond', 'fund',
    // Extended clean list
    'audit', 'basis', 'bytes', 'cross', 'depth', 'draft', 'early', 'epoch',
    'event', 'exact', 'faith', 'final', 'floor', 'float', 'grace', 'grant',
    'gross', 'guess', 'hoard', 'hopes', 'input', 'issue', 'ivory', 'joins',
    'joint', 'karma', 'keeps', 'kills', 'kings', 'known', 'large', 'later',
    'leads', 'learn', 'least', 'legal', 'lemon', 'level', 'lifts', 'light',
    'links', 'lists', 'longs', 'lower', 'lucky', 'marks', 'match', 'means',
    'merge', 'model', 'money', 'month', 'moral', 'moves', 'multi', 'needs',
    'never', 'night', 'noted', 'novel', 'offer', 'often', 'opens', 'other',
    'ought', 'outer', 'owned', 'owner', 'pairs', 'paper', 'parse', 'parts',
    'patch', 'pause', 'peaks', 'phase', 'pivot', 'pixel', 'plain', 'plan',
    'plate', 'plays', 'plaza', 'point', 'ports', 'power', 'press', 'prior',
    'prize', 'probe', 'proxy', 'pulls', 'pumps', 'query', 'queue', 'quick',
    'quiet', 'quite', 'radar', 'range', 'rates', 'reach', 'reads', 'ready',
    'realm', 'refer', 'reset', 'rider', 'rises', 'round', 'route', 'rules',
    'scale', 'scene', 'score', 'scope', 'scout', 'sends', 'sense', 'serve',
    'shape', 'share', 'shift', 'shook', 'sides', 'sight', 'since', 'sixth',
    'sized', 'skill', 'slack', 'slate', 'sleep', 'slice', 'slide', 'slope',
    'slows', 'small', 'smart', 'smile', 'snaps', 'solid', 'solve', 'sorts',
    'sound', 'space', 'spend', 'split', 'spoke', 'spots', 'stack', 'stage',
    'start', 'state', 'stays', 'steps', 'stick', 'still', 'stock', 'store',
    'storm', 'story', 'study', 'style', 'suite', 'super', 'swift', 'swing',
    'table', 'takes', 'talks', 'tasks', 'teams', 'terms', 'tests', 'their',
    'there', 'these', 'thick', 'thing', 'think', 'third', 'those', 'tight',
    'times', 'tired', 'title', 'today', 'tools', 'total', 'touch', 'tough',
    'tours', 'towns', 'track', 'trust', 'twice', 'types', 'under', 'union',
    'until', 'upper', 'usage', 'users', 'usual', 'valid', 'venue', 'views',
    'viral', 'vital', 'voted', 'watch', 'waves', 'weeks', 'whole', 'wider',
    'width', 'words', 'works', 'world', 'worry', 'worse', 'write', 'wrote',
    'years', 'zones',
  ];

  /// Valid guess words — includes answer words + common 5-letter English words.
  static const List<String> validGuesses = [
    // All answer words are valid guesses
    ...answerWords,
    // Additional common 5-letter words
    'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult',
    'after', 'again', 'agate', 'agent', 'agree', 'ahead', 'aimed', 'aired',
    'aisle', 'alarm', 'album', 'alert', 'alike', 'alive', 'alley', 'allow',
    'alone', 'along', 'aloud', 'altar', 'alter', 'amber', 'amend', 'angel',
    'anger', 'angle', 'angry', 'annex', 'antic', 'anvil', 'aorta', 'apple',
    'apply', 'arbor', 'argue', 'arise', 'armor', 'arose', 'array', 'arrow',
    'asked', 'attic', 'avail', 'avoid', 'aware', 'awful', 'badly', 'basic',
    'bears', 'beast', 'began', 'begin', 'below', 'bench', 'berry', 'birth',
    'blade', 'blame', 'bland', 'blaze', 'bleed', 'blend', 'bless', 'bliss',
    'blood', 'blown', 'boast', 'board', 'bonus', 'boost', 'booth', 'brave',
    'bread', 'break', 'breed', 'brick', 'brief', 'bring', 'brisk', 'broke',
    'brook', 'brown', 'brush', 'buddy', 'build', 'built', 'buoyant', 'buyer',
    'cabin', 'cable', 'camel', 'candy', 'cargo', 'carry', 'catch', 'cause',
    'cease', 'cedar', 'chalk', 'cheap', 'check', 'cheek', 'chess', 'chief',
    'child', 'chose', 'civic', 'civil', 'claim', 'clash', 'class', 'clean',
    'clear', 'clerk', 'cliff', 'climb', 'cling', 'clone', 'close', 'cloud',
    'clove', 'coach', 'coast', 'color', 'combo', 'comes', 'comma', 'coral',
    'count', 'court', 'covet', 'crack', 'craft', 'crane', 'crash', 'crave',
    'crawl', 'crazy', 'creek', 'creep', 'crisp', 'crown', 'crude', 'cruel',
    'crush', 'cubic', 'curve', 'cycle', 'daily', 'dance', 'dared', 'deals',
    'decoy', 'delay', 'dense', 'depot', 'debut', 'devil', 'dirty', 'disco',
    'doing', 'doubt', 'dough', 'downs', 'dozen', 'drama', 'drawn', 'dream',
    'dress', 'dried', 'drink', 'drive', 'drone', 'drove', 'drown', 'drunk',
    'dryer', 'dying', 'eager', 'eagle', 'earth', 'eight', 'eight', 'elite',
    'empty', 'ended', 'enemy', 'enjoy', 'enter', 'equal', 'error', 'essay',
    'every', 'evil', 'exist', 'extra', 'fable', 'faced', 'facto', 'false',
    'fancy', 'fatal', 'feast', 'fence', 'ferry', 'fetch', 'fever', 'fewer',
    'fifth', 'fifty', 'filed', 'first', 'fixed', 'flame', 'flash', 'flesh',
    'flier', 'fling', 'flood', 'flora', 'flour', 'flown', 'fluid', 'flute',
    'focal', 'focus', 'foggy', 'force', 'forge', 'forth', 'found', 'frame',
    'franc', 'frank', 'fraud', 'fresh', 'front', 'froze', 'fully', 'funny',
    'fuzzy', 'ghost', 'given', 'gland', 'glare', 'glass', 'glide', 'gloom',
    'glory', 'glove', 'going', 'gorge', 'gouge', 'gourd', 'grade', 'grail',
    'grams', 'grind', 'groan', 'grope', 'group', 'prove', 'growl', 'grown',
    'gruel', 'guide', 'guild', 'guile', 'guise', 'gusts', 'habit', 'harsh',
    'haunt', 'haven', 'heart', 'heavy', 'hertz', 'hippo', 'hobby', 'hotel',
    'hound', 'house', 'human', 'humid', 'humor', 'hurry', 'hyper', 'ideal',
    'imply', 'inbox', 'inner', 'intel', 'inter', 'intro', 'irony', 'jumbo',
    'keyed', 'kneel', 'knife', 'knots', 'label', 'labor', 'lance', 'lapse',
    'laser', 'laser', 'laugh', 'launched', 'lease', 'ledge', 'libel', 'liken',
    'liner', 'lingo', 'lions', 'liver', 'local', 'lodge', 'logic', 'loose',
    'lover', 'lowly', 'loyal', 'lucid', 'lunar', 'lying', 'magic', 'major',
    'maker', 'manor', 'maple', 'march', 'mason', 'maybe', 'media', 'mercy',
    'merit', 'metal', 'meter', 'midst', 'might', 'miles', 'mills', 'minus',
    'mirth', 'mixed', 'midst', 'moody', 'mouse', 'mouth', 'moved', 'mover',
    'movie', 'muddy', 'music', 'naive', 'named', 'narcs', 'nasty', 'natal',
    'naval', 'nerve', 'newly', 'noise', 'north', 'notch', 'nurse', 'occur',
    'ocean', 'olive', 'onset', 'overt', 'oxide', 'ozone', 'pasta', 'pedal',
    'penny', 'perch', 'perky', 'petty', 'phone', 'photo', 'piano', 'piece',
    'pilot', 'pinch', 'pinch', 'piped', 'pitch', 'place', 'plead', 'pluck',
    'plumb', 'plume', 'plunk', 'plush', 'polar', 'poser', 'posed', 'pouch',
    'prawn', 'preen', 'price', 'prick', 'pride', 'prime', 'print', 'prism',
    'privy', 'prod', 'prone', 'proud', 'prove', 'psalm', 'pubic', 'pulse',
    'punch', 'pupil', 'purge', 'purist', 'pylon', 'quake', 'queen', 'quirk',
    'quota', 'rabbi', 'racer', 'radio', 'raise', 'rangy', 'raven', 'rebel',
    'recut', 'remit', 'remix', 'rerun', 'reuse', 'rhyme', 'rider', 'rifle',
    'risky', 'rivet', 'roast', 'robot', 'rocky', 'rodeo', 'rouge', 'royal',
    'rugby', 'ruler', 'rusty', 'sadly', 'safer', 'saint', 'salve', 'salvo',
    'sandy', 'sauce', 'savor', 'savvy', 'scald', 'scamp', 'scant', 'scare',
    'scary', 'scoff', 'scold', 'scone', 'scoop', 'shack', 'shaft', 'shake',
    'shale', 'shall', 'shame', 'sharp', 'shear', 'sheen', 'sheer', 'shelf',
    'shell', 'shine', 'shire', 'shirt', 'shock', 'shore', 'short', 'shout',
    'shred', 'shrub', 'shrug', 'sided', 'siege', 'silky', 'silly', 'since',
    'sinew', 'siren', 'skate', 'skull', 'slant', 'sleet', 'slept', 'slick',
    'slung', 'smack', 'smash', 'smear', 'smell', 'smelt', 'smite', 'smoke',
    'snack', 'snaky', 'snare', 'sneak', 'snore', 'solar', 'sonar', 'sonic',
    'south', 'spam', 'spark', 'spare', 'spawn', 'spear', 'speck', 'speed',
    'spell', 'spice', 'spike', 'spill', 'spine', 'spite', 'splash', 'spoke',
    'spoon', 'spore', 'sport', 'spout', 'spray', 'spree', 'sprig', 'spunk',
    'squad', 'squat', 'squid', 'stab', 'staff', 'stain', 'stale', 'stall',
    'stamp', 'stand', 'stare', 'stark', 'stern', 'stiff', 'sting', 'stink',
    'stomp', 'stood', 'stoop', 'strap', 'straw', 'stray', 'strut', 'stuck',
    'stump', 'stung', 'stunk', 'stunt', 'sugar', 'sulky', 'sunny', 'surge',
    'swamp', 'swear', 'sweat', 'swept', 'swirl', 'swoon', 'swoop', 'taboo',
    'talon', 'tango', 'taunt', 'tense', 'tenth', 'tepid', 'terse', 'timer',
    'timid', 'tipsy', 'toast', 'token', 'tonal', 'topaz', 'torch', 'toxic',
    'trace', 'trans', 'trash', 'trial', 'tribe', 'trick', 'tried', 'troll',
    'troop', 'trout', 'truce', 'truly', 'trump', 'trunk', 'tuber', 'tulip',
    'tumor', 'tutor', 'tweak', 'twerp', 'twill', 'twirl', 'twist', 'ultra',
    'uncut', 'unfed', 'unfit', 'unity', 'unlit', 'unset', 'untie', 'upon',
    'upset', 'urban', 'utmost', 'utter', 'vapor', 'vaunt', 'vicar', 'vigor',
    'villa', 'vinyl', 'viola', 'viral', 'visit', 'visor', 'voice', 'voila',
    'vouch', 'vowel', 'vying', 'waged', 'wager', 'waist', 'waste', 'water',
    'weary', 'weave', 'wedge', 'woken', 'woman', 'women', 'woods', 'wrath',
    'wrist', 'yacht', 'yearn', 'yeast', 'young', 'yours', 'zonal',
  ];

  static bool isValidGuess(String word) {
    return validGuesses.contains(word.toLowerCase());
  }

  static String randomAnswerWord() {
    final now = DateTime.now();
    final dayIndex = now.difference(DateTime(2026, 1, 1)).inDays;
    return answerWords[dayIndex % answerWords.length];
  }
}
